added docker solution to run smoke tests
hmcts/sscs-track-your-appeal-frontend pull request #70
Opened 2018-05-23 11:50 UTC by satyachundur

Make sure the branch has the JIRA number in  https://tools.hmcts.net/jira/browse/SSCS-2761

2018-06-04 14:17 UTC, bendiggle requested changes

2018-06-04 14:17 UTC, bendiggle commented on test/e2e/codecept.conf.js
> +      url: process.env.FRONTEND_URL || 'https://localhost:3000',
This can be left as `config.get('e2e.frontendUrl')` as it does the same thing as above.

2018-06-04 14:17 UTC, bendiggle commented on bin/run-tests.sh
> +shutdownDocker
needs a new line here

2018-06-04 14:17 UTC, bendiggle commented on test/e2e/smoke/accessCaseDetail.test.js
> +  // Content.
Remove the comment and space between

2018-06-06 15:20 UTC, satyachundur commented
As we have chrome installed on jenkins.  Closing this PR

2018-06-06 15:20 UTC, closed without merging